export const cityList = [
  { name: "Amsterdam", timezone: "Europe/Amsterdam" },
  { name: "Athens", timezone: "Europe/Athens" },
  { name: "Bangkok", timezone: "Asia/Bangkok" },
  { name: "Barcelona", timezone: "Europe/Madrid" },
  { name: "Beijing", timezone: "Asia/Shanghai" },
  { name: "Berlin", timezone: "Europe/Berlin" },
  { name: "Buenos Aires", timezone: "America/Argentina/Buenos_Aires" },
  { name: "Cairo", timezone: "Africa/Cairo" },
  { name: "Chicago", timezone: "America/Chicago" },
  { name: "Copenhagen", timezone: "Europe/Copenhagen" },
  { name: "Delhi", timezone: "Asia/Kolkata" },
  { name: "Dubai", timezone: "Asia/Dubai" },
  { name: "Dublin", timezone: "Europe/Dublin" },
  { name: "Frankfurt", timezone: "Europe/Berlin" },
  { name: "Helsinki", timezone: "Europe/Helsinki" },
  { name: "Hong Kong", timezone: "Asia/Hong_Kong" },
  { name: "Istanbul", timezone: "Europe/Istanbul" },
  { name: "Jakarta", timezone: "Asia/Jakarta" },
  { name: "Jerusalem", timezone: "Asia/Jerusalem" },
  { name: "Johannesburg", timezone: "Africa/Johannesburg" },
  { name: "Kuala Lumpur", timezone: "Asia/Kuala_Lumpur" },
  { name: "Lagos", timezone: "Africa/Lagos" },
  { name: "Lima", timezone: "America/Lima" },
  { name: "Lisbon", timezone: "Europe/Lisbon" },
  { name: "London", timezone: "Europe/London" },
  { name: "Los Angeles", timezone: "America/Los_Angeles" },
  { name: "Madrid", timezone: "Europe/Madrid" },
  { name: "Manila", timezone: "Asia/Manila" },
  { name: "Melbourne", timezone: "Australia/Melbourne" },
  { name: "Mexico City", timezone: "America/Mexico_City" },
  { name: "Miami", timezone: "America/New_York" },
  { name: "Milan", timezone: "Europe/Rome" },
  { name: "Montreal", timezone: "America/Toronto" },
  { name: "Moscow", timezone: "Europe/Moscow" },
  { name: "Mumbai", timezone: "Asia/Kolkata" },
  { name: "Munich", timezone: "Europe/Berlin" },
  { name: "Nairobi", timezone: "Africa/Nairobi" },
  { name: "New Delhi", timezone: "Asia/Kolkata" },
  { name: "New York", timezone: "America/New_York" },
  { name: "Oslo", timezone: "Europe/Oslo" },
  { name: "Paris", timezone: "Europe/Paris" },
  { name: "Prague", timezone: "Europe/Prague" },
  { name: "Rio de Janeiro", timezone: "America/Sao_Paulo" },
  { name: "Rome", timezone: "Europe/Rome" },
  { name: "San Francisco", timezone: "America/Los_Angeles" },
  { name: "Santiago", timezone: "America/Santiago" },
  { name: "São Paulo", timezone: "America/Sao_Paulo" },
  { name: "Seoul", timezone: "Asia/Seoul" },
  { name: "Shanghai", timezone: "Asia/Shanghai" },
  { name: "Singapore", timezone: "Asia/Singapore" },
  { name: "Stockholm", timezone: "Europe/Stockholm" },
  { name: "Sydney", timezone: "Australia/Sydney" },
  { name: "Taipei", timezone: "Asia/Taipei" },
  { name: "Tokyo", timezone: "Asia/Tokyo" },
  { name: "Toronto", timezone: "America/Toronto" },
  { name: "Vancouver", timezone: "America/Vancouver" },
  { name: "Vienna", timezone: "Europe/Vienna" },
  { name: "Warsaw", timezone: "Europe/Warsaw" },
  { name: "Washington DC", timezone: "America/New_York" },
  { name: "Zurich", timezone: "Europe/Zurich" }
];